package vista;

import controladorBO.controladorBO;
import javax.swing.JOptionPane;
import modeloVO.modeloVO;

public class VistaReto5 extends javax.swing.JFrame {

    public VistaReto5() {
        initComponents();
        ButActualizar.setEnabled(false);
        ButEliminar.setEnabled(false);
    }
    
    public void limpiar(){
        txtNombres.setText(null);
        txtApellidos.setText(null);
        txtNacimiento.setText(null);
        txtCorreoInst.setText(null);
        txtCorreoPers.setText(null);
        txtCelular.setText(null);
        txtFijo.setText(null);
        txtCarrera.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LNombre = new javax.swing.JLabel();
        LApellidos = new javax.swing.JLabel();
        LNacimiento = new javax.swing.JLabel();
        LCorreoInst = new javax.swing.JLabel();
        LCorreoPers = new javax.swing.JLabel();
        LCelular = new javax.swing.JLabel();
        LFijo = new javax.swing.JLabel();
        LCarrera = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtCorreoInst = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtNacimiento = new javax.swing.JTextField();
        txtCarrera = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtFijo = new javax.swing.JTextField();
        txtCorreoPers = new javax.swing.JTextField();
        ButInsertar = new javax.swing.JButton();
        ButCargar = new javax.swing.JButton();
        ButActualizar = new javax.swing.JButton();
        ButEliminar = new javax.swing.JButton();
        ButConsultas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LNombre.setText("Nombres");

        LApellidos.setText("Apellidos");

        LNacimiento.setText("Nacimiento");

        LCorreoInst.setText("Correo institucional");

        LCorreoPers.setText("Correo personal");

        LCelular.setText("Teléfono celular");

        LFijo.setText("Teléfono fijo");

        LCarrera.setText("Programa");

        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });

        txtCorreoInst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoInstActionPerformed(evt);
            }
        });

        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });

        txtNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNacimientoActionPerformed(evt);
            }
        });

        txtCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarreraActionPerformed(evt);
            }
        });

        txtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularActionPerformed(evt);
            }
        });

        txtFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFijoActionPerformed(evt);
            }
        });

        txtCorreoPers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoPersActionPerformed(evt);
            }
        });

        ButInsertar.setText("Insertar");
        ButInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButInsertarActionPerformed(evt);
            }
        });

        ButCargar.setText("Cargar");
        ButCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCargarActionPerformed(evt);
            }
        });

        ButActualizar.setText("Actualizar");
        ButActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButActualizarActionPerformed(evt);
            }
        });

        ButEliminar.setText("Eliminar");
        ButEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButEliminarActionPerformed(evt);
            }
        });

        ButConsultas.setText("Consultas");
        ButConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButConsultasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LCorreoInst)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LNombre)
                            .addComponent(LApellidos)
                            .addComponent(LNacimiento)
                            .addComponent(LCarrera)
                            .addComponent(LFijo)
                            .addComponent(LCelular)
                            .addComponent(LCorreoPers))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFijo, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorreoPers, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorreoInst, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ButInsertar)
                        .addGap(18, 18, 18)
                        .addComponent(ButCargar)
                        .addGap(18, 18, 18)
                        .addComponent(ButActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(ButEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(ButConsultas)
                        .addGap(61, 61, 61)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNombre)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LApellidos)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNacimiento)
                    .addComponent(txtNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LCorreoInst)
                    .addComponent(txtCorreoInst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LCorreoPers)
                    .addComponent(txtCorreoPers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LCelular)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LFijo)
                    .addComponent(txtFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LCarrera)
                    .addComponent(txtCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButInsertar)
                    .addComponent(ButCargar)
                    .addComponent(ButActualizar)
                    .addComponent(ButEliminar)
                    .addComponent(ButConsultas))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void txtCorreoInstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoInstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoInstActionPerformed

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void txtNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNacimientoActionPerformed

    private void txtCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarreraActionPerformed

    private void txtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularActionPerformed

    private void txtFijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFijoActionPerformed

    private void txtCorreoPersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoPersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoPersActionPerformed

    private void ButInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButInsertarActionPerformed
        //Boton insertar
        modeloVO nuevo = new modeloVO();
        nuevo.setNombres(txtNombres.getText());
        nuevo.setApellidos(txtApellidos.getText());
        nuevo.setNacimiento(txtNacimiento.getText());
        nuevo.setCorreoInst(txtCorreoInst.getText());
        nuevo.setCorreoPers(txtCorreoPers.getText());
        nuevo.setCelular(Long.parseLong(txtCelular.getText()));
        nuevo.setFijo(Long.parseLong(txtFijo.getText()));
        nuevo.setCarrera(txtCarrera.getText());
        
        boolean resultado = new controladorBO().insertarEstudiante(nuevo);
        String mensaje = resultado?"El estudiante fue registrado":"El estudiante no fue registrado";
        limpiar();
        ButActualizar.setEnabled(false);
        ButEliminar.setEnabled(false);
        JOptionPane.showMessageDialog(this, mensaje);
    }//GEN-LAST:event_ButInsertarActionPerformed

    private void ButActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButActualizarActionPerformed
        String CorreoInst = txtCorreoInst.getText();
        modeloVO encontrado = new controladorBO().obtenerEstudiante(CorreoInst);
        encontrado.setNombres(txtNombres.getText());
        encontrado.setApellidos(txtApellidos.getText());
        encontrado.setNacimiento(txtNacimiento.getText());
        encontrado.setCorreoInst(txtCorreoInst.getText());
        encontrado.setCorreoPers(txtCorreoPers.getText());
        encontrado.setCelular(Long.parseLong(txtCelular.getText()));
        encontrado.setFijo(Long.parseLong(txtFijo.getText()));
        encontrado.setCarrera(txtCarrera.getText());
        boolean resultado = new controladorBO().actualizarEstudiante(encontrado);
        limpiar();
        String mensaje = resultado?"El estudiante ha sido actualizado":"El estudiante no se actualizó";
        
        JOptionPane.showMessageDialog(this, mensaje);
    }//GEN-LAST:event_ButActualizarActionPerformed

    private void ButCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCargarActionPerformed
        String CorreoInst = txtCorreoInst.getText();
        modeloVO encontrado = new controladorBO().obtenerEstudiante(CorreoInst);
        if(encontrado != null){
            txtNombres.setText(encontrado.getNombres());
            txtApellidos.setText(encontrado.getApellidos());
            txtNacimiento.setText(encontrado.getNacimiento());
            txtCorreoInst.setText(encontrado.getCorreoInst());
            txtCorreoPers.setText(encontrado.getCorreoPers());
            txtCelular.setText(encontrado.getCelular() + "");
            txtFijo.setText(encontrado.getFijo() + "");
            txtCarrera.setText(encontrado.getCarrera());
        }else{
            JOptionPane.showMessageDialog(this, "Estudiante no encontrado");
            JOptionPane.showMessageDialog(this, "Ingrese el correo del estudiante");
        }
        ButActualizar.setEnabled(true);
        ButEliminar.setEnabled(true);
    }//GEN-LAST:event_ButCargarActionPerformed

    private void ButEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButEliminarActionPerformed
        String CorreoInst = txtCorreoInst.getText();
        modeloVO estudiante = new controladorBO().obtenerEstudiante(CorreoInst);
        boolean resultado = new controladorBO().eliminarEstudiante(estudiante);
        limpiar();
        String mensaje = resultado?"El estudiante fue eliminado":"El estudiante no fue eliminado";
        JOptionPane.showMessageDialog(this, mensaje);
    }//GEN-LAST:event_ButEliminarActionPerformed

    private void ButConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButConsultasActionPerformed
        new Consultas(this, true).setVisible(true);
    }//GEN-LAST:event_ButConsultasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaReto5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaReto5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaReto5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaReto5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaReto5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButActualizar;
    private javax.swing.JButton ButCargar;
    private javax.swing.JButton ButConsultas;
    private javax.swing.JButton ButEliminar;
    private javax.swing.JButton ButInsertar;
    private javax.swing.JLabel LApellidos;
    private javax.swing.JLabel LCarrera;
    private javax.swing.JLabel LCelular;
    private javax.swing.JLabel LCorreoInst;
    private javax.swing.JLabel LCorreoPers;
    private javax.swing.JLabel LFijo;
    private javax.swing.JLabel LNacimiento;
    private javax.swing.JLabel LNombre;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCarrera;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCorreoInst;
    private javax.swing.JTextField txtCorreoPers;
    private javax.swing.JTextField txtFijo;
    private javax.swing.JTextField txtNacimiento;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
